### ISSUE TITLE
Charts disappear in portfolio when certain coins added

### ISSUE THREAD

**Issue by smogger** [ismaelestalayo/CryptoTracker#23]
### **BUG:**

If you add certain coins to your portfolio, the whole chart disappears.

SGB - Songbird
EXFI - Flare Finance

The strange thing is that the app is capable to retrieve SGB price, yet the chart is not visible. 

### **Feature request:**
Would be nice to have a confirmation pop-up under the portfolio if you plan to remove one coin. If you have a lot of transactions stored under that coin it is not a really pleasant experience if you accidentally remove it. Especially because the "see coin" is just next to it.

Thank you

**Comment by ismaelestalayo** [comment]
Thanks for the heads up about this double issue. In one hand I'll try to fix the empty charts on these coins (which I guess they are not supported in one of the three APIs I use), and in the other hand, there really should be a warning message when deleting more than one purchase as you said, so i'll add that as well.
Thanks

**Comment by ismaelestalayo** [comment]
Sorry for taking so long to fix this issue, but it has finally been fixed in the latest version v6.1.4.

The problem happened with coin-pairs not supported in CryptoCompare, like EXFI-EUR or EXFI-USD for example. For now, that coin will not be counted in the historic chart of the Portfolio.

While fixing this bug I also found that some alt-coins had no price data, and could alter the portfolio negatively, so I've added a warning symbol to let users know:
![image](https://user-images.githubusercontent.com/17100634/156718677-6d8da30c-67ee-4be3-bbe6-720e811bd942.png)
